# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo %CD%
    c:\LDRA_Toolsuite_C_CPP_10.0.3\contestbed blocksort.c /11234q
    c:\LDRA_Toolsuite_C_CPP_10.0.3\tbreports C:\LDRA_Workarea_C_CPP_10.0.3\Tbwrkfls\blocksort_1.ldra -tbpublish -tbpublish_dir=%CD%\TestResults

  displayName: 'Run a multi-line script'

- task: PublishHtmlReport@1
  inputs:
    tabName: 'LDRA Results'
    reportDir: 'TestResults'
